import type { ApiDefinition } from "./types.js";

export const canvasApis: ApiDefinition[] = [
  {
    key: "*.getContext",
    argMatch: ["2d"],
    category: "canvas",
    severity: "medium",
    description: "Acquires a 2D canvas context — almost always a prelude to canvas fingerprinting.",
    evasion: "Hooking is detectable; safer to inject sub-pixel noise into ImageData before toDataURL/toBlob to defeat hash-based fingerprints while keeping a stable persona.",
  },
  {
    key: "*.toDataURL",
    category: "canvas",
    severity: "high",
    botDetectionTell: true,
    layer: "L1a",
    description: "Serializes a canvas to a base64 PNG/JPEG. The most common canvas-fingerprinting sink.",
    evasion: "Patch HTMLCanvasElement.prototype.toDataURL to perturb the underlying ImageData first; persist noise per-session for stability.",
  },
  {
    key: "*.toBlob",
    category: "canvas",
    severity: "high",
    botDetectionTell: true,
    layer: "L1a",
    description: "Async sibling of toDataURL — identical fingerprint risk.",
  },
  {
    key: "*.getImageData",
    category: "canvas",
    severity: "high",
    botDetectionTell: true,
    layer: "L1a",
    description: "Reads pixel data directly. Bypasses toDataURL hooks; intercept here too if defending.",
  },
  {
    key: "*.fillText",
    category: "canvas",
    severity: "medium",
    description: "Fingerprinting scripts paint a known glyph string and read pixels back. fillText use near getImageData/toDataURL is the canonical pattern.",
  },
  {
    key: "*.strokeText",
    category: "canvas",
    severity: "medium",
    description: "Companion to fillText; rasterization differences across font stacks/GPUs leak entropy.",
  },
  {
    key: "*.measureText",
    category: "canvas",
    severity: "medium",
    description: "Returns a TextMetrics. Width and bounding-box numbers vary per font and system.",
  },
  {
    key: "*.isPointInPath",
    category: "canvas",
    severity: "low",
    description: "Used in some uncommon canvas probes.",
  },
  {
    key: "*.createImageData",
    category: "canvas",
    severity: "info",
    description: "Allocates a blank ImageData buffer.",
  },
  {
    key: "*.putImageData",
    category: "canvas",
    severity: "info",
    description: "Writes pixels back to a canvas.",
  },
  {
    key: "*.beginPath",
    category: "canvas",
    severity: "info",
    description: "Path construction; not fingerprint-critical on its own.",
  },
  {
    key: "*.arc",
    category: "canvas",
    severity: "info",
    description: "Path construction; sometimes used in canvas probes.",
  },
  {
    key: "*.fill",
    category: "canvas",
    severity: "info",
    description: "Fills the current path.",
  },
  {
    key: "*.stroke",
    category: "canvas",
    severity: "info",
    description: "Strokes the current path.",
  },
  {
    key: "*.fillRect",
    category: "canvas",
    severity: "info",
    description: "Fills a rectangle. Appears as part of canvas fingerprint setup (background).",
  },
  {
    key: "*.clearRect",
    category: "canvas",
    severity: "info",
    description: "Clears a rectangle.",
  },
  {
    key: "*.moveTo",
    category: "canvas",
    severity: "info",
    description: "Path move; common in canvas fingerprint test images.",
  },
  {
    key: "*.lineTo",
    category: "canvas",
    severity: "info",
    description: "Path line; canvas fingerprint setup.",
  },
  {
    key: "*.ellipse",
    category: "canvas",
    severity: "info",
    description: "Path ellipse; part of canvas-fingerprint shape suites.",
  },
  {
    key: "*.bezierCurveTo",
    category: "canvas",
    severity: "info",
    description: "Path bezier; rare outside canvas-fingerprint test images.",
  },
  {
    key: "*.quadraticCurveTo",
    category: "canvas",
    severity: "info",
    description: "Path quadratic; rare outside canvas-fingerprint test images.",
  },
  {
    key: "*.createRadialGradient",
    category: "canvas",
    severity: "low",
    description: "Radial gradient; commonly used in canvas-fingerprint setup to elicit GPU-blend variance.",
  },
  {
    key: "*.createLinearGradient",
    category: "canvas",
    severity: "low",
    description: "Linear gradient; same fingerprint role as createRadialGradient.",
  },
  {
    key: "*.addColorStop",
    category: "canvas",
    severity: "info",
    description: "Gradient stop; appears with createRadialGradient/createLinearGradient.",
  },
  {
    key: "*.actualBoundingBoxAscent",
    category: "canvas",
    severity: "high",
    botDetectionTell: true,
    description: "TextMetrics.actualBoundingBoxAscent. Sub-pixel glyph metric exposed via measureText(). Strong font-render fingerprint.",
  },
  {
    key: "*.actualBoundingBoxDescent",
    category: "canvas",
    severity: "high",
    botDetectionTell: true,
    description: "TextMetrics.actualBoundingBoxDescent. Same axis as ascent.",
  },
  {
    key: "*.actualBoundingBoxLeft",
    category: "canvas",
    severity: "medium",
    description: "TextMetrics.actualBoundingBoxLeft.",
  },
  {
    key: "*.actualBoundingBoxRight",
    category: "canvas",
    severity: "medium",
    description: "TextMetrics.actualBoundingBoxRight.",
  },
  {
    key: "*.fontBoundingBoxAscent",
    category: "canvas",
    severity: "medium",
    description: "TextMetrics.fontBoundingBoxAscent — font-level metric (vs glyph-level).",
  },
  {
    key: "*.fontBoundingBoxDescent",
    category: "canvas",
    severity: "medium",
    description: "TextMetrics.fontBoundingBoxDescent.",
  },
];
