import type { ApiDefinition } from "./types.js";

export const documentApis: ApiDefinition[] = [
  {
    key: "document.cookie",
    category: "document",
    severity: "low",
    description: "Cookie jar access. Checked for presence and for specific anti-bot cookies (Akamai _abck, Cloudflare cf_clearance, DataDome).",
  },
  {
    key: "document.referrer",
    category: "document",
    severity: "low",
    description: "Referring URL. Empty on direct nav; checked alongside Referer header.",
  },
  {
    key: "document.hidden",
    category: "document",
    severity: "low",
    description: "Page Visibility API; false in foreground tabs.",
  },
  {
    key: "document.visibilityState",
    category: "document",
    severity: "low",
    description: "Companion to .hidden ('visible'/'hidden'/'prerender').",
  },
  {
    key: "document.hasFocus",
    category: "document",
    severity: "low",
    description: "True if document has focus. Headless windows often lack focus events.",
  },
  {
    key: "document.characterSet",
    category: "document",
    severity: "info",
    description: "Document character encoding.",
  },
  {
    key: "document.documentElement",
    category: "document",
    severity: "info",
    description: "Root element; typical entry point for client-rect / layout fingerprinting.",
  },
  {
    key: "document.body",
    category: "document",
    severity: "info",
    description: "Body element; sometimes attribute-checked for automation tells.",
  },
  {
    key: "document.createElement",
    category: "document",
    severity: "low",
    description: "Used to construct probe elements (canvas, audio, video) for fingerprinting.",
    evasion: "Tag-name argument often reveals intent: `createElement('canvas')` or `createElement('iframe')` for cross-frame property probes.",
  },
  {
    key: "document.fonts",
    category: "document",
    severity: "medium",
    description: "FontFaceSet. Detectors enumerate, call check()/load() on probe families to fingerprint installed fonts.",
  },
  {
    key: "document.implementation",
    category: "document",
    severity: "info",
    description: "DOMImplementation; rarely fingerprinted.",
  },
  {
    key: "document.styleSheets",
    category: "document",
    severity: "low",
    description: "Live StyleSheetList. Iterating + reading .cssRules exposes the engine's CSS-property normalization (shorthand expansion order, default values).",
  },
  {
    key: "document.currentScript",
    category: "document",
    severity: "medium",
    description: "Reference to the executing <script> element. Detectors read .src and fetch the URL back to verify byte-for-byte integrity of their loaded blob.",
    botDetectionTell: true,
  },
  {
    key: "document.createElementNS",
    category: "document",
    severity: "low",
    description: "Namespaced element creation. Common for SVG fingerprint probes (createElementNS('http://www.w3.org/2000/svg', 'text')).",
  },
  {
    key: "document.createRange",
    category: "document",
    severity: "medium",
    description: "Range constructor. Range.getBoundingClientRect of a selected text node is a font-fingerprint path that bypasses canvas hooks.",
    botDetectionTell: true,
  },
  {
    key: "document.timeline",
    category: "document",
    severity: "info",
    description: "DocumentTimeline.currentTime. Subtle high-resolution clock alternative to performance.now().",
  },
  {
    key: "document.createEvent",
    category: "document",
    severity: "low",
    description: "Legacy event factory. createEvent('TouchEvent') is a touch-capability probe that throws on non-touch browsers.",
  },
  {
    key: "*.contentWindow",
    category: "document",
    severity: "high",
    botDetectionTell: true,
    description: "HTMLIFrameElement.contentWindow. Detectors create a hidden iframe and re-read navigator.webdriver / window.chrome / Notification.permission from the iframe's pristine realm — bypasses main-window patches.",
    evasion: "Hook HTMLIFrameElement.prototype.contentWindow / .contentDocument getters, or override the constructors of iframe-side classes (Navigator.prototype) so the same patches apply to every realm.",
  },
  {
    key: "*.contentDocument",
    category: "document",
    severity: "high",
    botDetectionTell: true,
    description: "Same cross-realm escape hatch as contentWindow.",
  },
  {
    key: "CookieStore",
    category: "document",
    severity: "low",
    description: "Async cookie API constructor — capability probe (Chrome 87+).",
  },
  {
    key: "cookieStore",
    category: "document",
    severity: "low",
    description: "Global async cookie API. get/getAll bypass document.cookie strict-domain rules.",
  },
  {
    key: "document.adoptedStyleSheets",
    category: "document",
    severity: "medium",
    description: "Document.adoptedStyleSheets. Live list of constructable stylesheets attached to the document. Extension-injected styles often appear here even when hidden from document.styleSheets.",
  },
  {
    key: "*.adoptedStyleSheets",
    category: "document",
    severity: "medium",
    description: "ShadowRoot.adoptedStyleSheets; same axis.",
  },
];
