import type { ApiDefinition } from "./types.js";

export const eventsDomApis: ApiDefinition[] = [
  {
    key: "*.addEventListener",
    category: "events",
    severity: "info",
    description: "Generic listener install. Fingerprint-relevant when the event name is 'mousemove', 'mousedown', 'pointermove', 'devicemotion', or 'deviceorientation' — used to score human-like input.",
    evasion: "If you detect synthetic input, generate plausibly noisy mouse paths and dispatch via CDP Input.dispatchMouseEvent (untrusted) or via real OS-level injection (trusted) before the page loads its handlers.",
  },
  {
    key: "*.dispatchEvent",
    category: "events",
    severity: "low",
    description: "Synthetic event dispatch. Detectors check `event.isTrusted` — synthetic events are flagged.",
  },
  {
    key: "*.getBoundingClientRect",
    category: "dom-layout",
    severity: "medium",
    description: "Geometry probe. Sub-pixel rect values vary across font-stack/zoom/DPR combinations and are stable per environment.",
  },
  {
    key: "*.getClientRects",
    category: "dom-layout",
    severity: "medium",
    description: "Multi-rect geometry probe; same fingerprint axis as getBoundingClientRect.",
  },
  {
    key: "MutationObserver",
    category: "dom-layout",
    severity: "info",
    description: "Used both by detectors (to spot late DOM tampering) and by stealth shims (to re-apply patches).",
  },
  {
    key: "matchMedia",
    category: "dom-layout",
    severity: "low",
    description: "Media-query probes. `(prefers-color-scheme)`, `(prefers-reduced-motion)`, `(forced-colors)`, `(any-pointer)`, `(hover)` all add fingerprint entropy.",
  },
  {
    key: "IntersectionObserver",
    category: "dom-layout",
    severity: "info",
    description: "Constructor capability probe.",
  },
  {
    key: "ResizeObserver",
    category: "dom-layout",
    severity: "info",
    description: "Constructor capability probe.",
  },
  {
    key: "PerformanceObserver",
    category: "dom-layout",
    severity: "info",
    description: "Constructor capability probe — paired with observe('longtask', 'paint', 'measure').",
  },
  {
    key: "ReportingObserver",
    category: "dom-layout",
    severity: "low",
    description: "Brave-resistance fingerprint axis (Brave / Tor return null for new ReportingObserver options).",
  },
  {
    key: "*.observe",
    category: "dom-layout",
    severity: "info",
    description: "Generic .observe() call; alone not meaningful, but co-occurrence with PerformanceObserver near timing fingerprints is.",
  },
  {
    key: "*.isTrusted",
    category: "events",
    severity: "high",
    botDetectionTell: true,
    layer: "L1b",
    description: "Event.isTrusted. Synthetic events dispatched via dispatchEvent or CDP Input.dispatchMouseEvent (without untrusted=false) read as false — direct automation tell.",
    evasion: "Real OS-level input injection or CDP with proper trusted-context flags. Hooking isTrusted requires patching Event.prototype getters.",
  },
  {
    key: "*.movementX",
    category: "events",
    severity: "medium",
    layer: "L1b",
    description: "MouseEvent.movementX. Distribution of mouse-movement deltas; bots produce straight-line / constant-velocity tracks that classifiers separate from human noise.",
    botDetectionTell: true,
  },
  {
    key: "*.movementY",
    category: "events",
    severity: "medium",
    layer: "L1b",
    description: "MouseEvent.movementY.",
  },
  {
    key: "*.pressure",
    category: "events",
    severity: "medium",
    layer: "L1b",
    description: "PointerEvent.pressure. Touch/pen events should report sub-1 values; mouse always 0.5. Constant or NaN under headless automation.",
    botDetectionTell: true,
  },
  {
    key: "*.tangentialPressure",
    category: "events",
    severity: "low",
    description: "PointerEvent.tangentialPressure. Always 0 unless a real pen is in use.",
  },
  {
    key: "*.tiltX",
    category: "events",
    severity: "low",
    description: "PointerEvent.tiltX. Pen tilt; 0 unless real input.",
  },
  {
    key: "*.tiltY",
    category: "events",
    severity: "low",
    description: "PointerEvent.tiltY.",
  },
  {
    key: "*.timeStamp",
    category: "events",
    severity: "low",
    description: "Event.timeStamp. Inter-event delta histogram — bots produce uniform deltas, humans don't.",
  },
  {
    key: "*.elementFromPoint",
    category: "dom-layout",
    severity: "medium",
    layer: "L3",
    description: "document.elementFromPoint(x,y). Honeypot-link probing: detectors hide an invisible anchor at known coords; if elementFromPoint returns it AND a click event ever fires on it, the visitor is a bot.",
    botDetectionTell: true,
  },
  {
    key: "*.elementsFromPoint",
    category: "dom-layout",
    severity: "low",
    description: "document.elementsFromPoint(x,y). Same honeypot vector as elementFromPoint.",
  },

  // ─── Keystroke biometrics (TypeNet, 2012 Mouse+Keystroke Dynamics) ─────────
  // Inter-key dwell and flight times are the inputs to keystroke-
  // biometrics classifiers. Bots produce uniform deltas; humans don't.
  // SoK §3.4 L1b — survives Operator Synthesis only when the orchestration
  // layer injects realistic keystroke kinematics.
  {
    key: "*.key",
    category: "events",
    severity: "low",
    description: "KeyboardEvent.key. Logical key value (e.g. 'a', 'Shift'). Inputs to keystroke-dynamics classifiers.",
  },
  {
    key: "*.code",
    category: "events",
    severity: "low",
    layer: "L1b",
    description: "KeyboardEvent.code. Physical key identifier ('KeyA', 'ShiftLeft'). Inconsistency between .key and .code distribution distinguishes keyboard layouts and detects programmatic dispatch.",
    botDetectionTell: true,
  },
  {
    key: "*.repeat",
    category: "events",
    severity: "low",
    layer: "L1b",
    description: "KeyboardEvent.repeat. True when the OS is auto-repeating a held key. Synthetic typers (CDP, robotjs) almost never set this — constant `false` across a long key sequence is a tell.",
    botDetectionTell: true,
  },
  {
    key: "*.location",
    category: "events",
    severity: "info",
    description: "KeyboardEvent.location (0-3 = standard / left / right / numpad). Used to fingerprint physical keyboard layout via shift-side preference in detected sequences.",
  },
  {
    key: "*.isComposing",
    category: "events",
    severity: "low",
    description: "KeyboardEvent.isComposing / InputEvent.isComposing. Pins IME usage — locale + platform tell.",
  },
  {
    key: "*.charCode",
    category: "events",
    severity: "info",
    description: "Legacy KeyboardEvent.charCode. Reads through deprecated path; some old detectors still rely on it.",
  },
  {
    key: "*.keyCode",
    category: "events",
    severity: "info",
    description: "Legacy KeyboardEvent.keyCode. Same axis as .charCode.",
  },

  // ─── Wheel / scroll dynamics (BeCAPTCHA-Mouse appendix) ────────────────────
  {
    key: "*.deltaX",
    category: "events",
    severity: "medium",
    layer: "L1b",
    description: "WheelEvent.deltaX. Scroll-velocity profile across multi-event sequences. Constant deltas → synthetic scroll.",
    botDetectionTell: true,
  },
  {
    key: "*.deltaY",
    category: "events",
    severity: "medium",
    layer: "L1b",
    description: "WheelEvent.deltaY. Same axis as deltaX.",
    botDetectionTell: true,
  },
  {
    key: "*.deltaZ",
    category: "events",
    severity: "low",
    description: "WheelEvent.deltaZ. Rarely populated; reading it is usually scaffolding for a fuller wheel-fingerprint pass.",
  },
  {
    key: "*.deltaMode",
    category: "events",
    severity: "low",
    description: "WheelEvent.deltaMode (0 = pixel, 1 = line, 2 = page). Trackpad vs mousewheel vs OS-level scroll source — coarse hardware tell.",
  },

  // ─── Input / Pointer disambiguation ────────────────────────────────────────
  {
    key: "*.inputType",
    category: "events",
    severity: "low",
    layer: "L1b",
    description: "InputEvent.inputType ('insertText', 'insertCompositionText', 'deleteContentBackward', …). Inferred typing modality (autocomplete, paste, IME) — discriminates programmatic value-set from real typing.",
    botDetectionTell: true,
  },
  {
    key: "*.data",
    category: "events",
    severity: "info",
    description: "InputEvent.data. The composed text fragment. Often paired with .inputType for IME / paste analysis.",
  },
  {
    key: "*.pointerType",
    category: "events",
    severity: "medium",
    layer: "L1b",
    description: "PointerEvent.pointerType ('mouse' | 'pen' | 'touch'). Cross-checked with navigator.maxTouchPoints, userAgentData.mobile, and TouchEvent presence — common consistency-failure axis for headless setups claiming a mobile UA.",
    botDetectionTell: true,
  },
  {
    key: "*.pointerId",
    category: "events",
    severity: "info",
    description: "PointerEvent.pointerId. Multi-touch session identity; rarely a tell on its own.",
  },
  {
    key: "*.composedPath",
    category: "events",
    severity: "medium",
    layer: "L1b",
    description: "Event.composedPath(). Returns the propagation path including shadow-DOM ancestry. Synthetic events dispatched via dispatchEvent without a real target reveal themselves through an unexpected path shape — pair with .isTrusted for the strongest signal.",
    botDetectionTell: true,
  },
  {
    key: "*.getModifierState",
    category: "events",
    severity: "low",
    description: "KeyboardEvent.getModifierState / MouseEvent.getModifierState. Reads lock states (NumLock, CapsLock, ScrollLock) that bot drivers can't easily fake without OS-level injection.",
  },
  {
    key: "*.screenX",
    category: "events",
    severity: "low",
    description: "MouseEvent.screenX. Absolute screen-space cursor coords (vs clientX/Y for viewport-space). Distribution + drift over a session input mouse-kinematics models (BeCAPTCHA-Mouse, 2020).",
  },
  {
    key: "*.screenY",
    category: "events",
    severity: "low",
    description: "MouseEvent.screenY. Same axis as screenX.",
  },
  {
    key: "*.clientX",
    category: "events",
    severity: "info",
    description: "MouseEvent.clientX. Viewport-relative cursor coords; weakly load-bearing alone, strongly load-bearing as a kinematic-trace input.",
  },
  {
    key: "*.clientY",
    category: "events",
    severity: "info",
    description: "MouseEvent.clientY. Same as clientX.",
  },
];
