import type { ApiDefinition } from "./types.js";

export const introspectionApis: ApiDefinition[] = [
  {
    key: "Function.prototype.toString",
    category: "introspection",
    severity: "high",
    botDetectionTell: true,
    layer: "L2",
    description: "Source-of-function probe. Detectors call .toString() on patched native methods (e.g., navigator.permissions.query) and check it returns `function name() { [native code] }`. Monkey-patches that don't impersonate native source are flagged.",
    evasion: "Override Function.prototype.toString to return canonical native-source for patched methods, OR define patches via Object.defineProperty getters that the proxy chain resolves cleanly. Stealth scripts handle this.",
  },
  {
    key: "*.toString",
    category: "introspection",
    severity: "low",
    description: "Generic .toString call — could be the function probe above or could be benign string conversion.",
  },
  {
    key: "Object.getOwnPropertyDescriptor",
    category: "introspection",
    severity: "medium",
    description: "Reads property descriptors. Used to detect getter overrides (a getter that wasn't there before) and to verify [[Configurable]] / [[Writable]] match real-Chrome shape.",
    botDetectionTell: true,
  },
  {
    key: "Object.getOwnPropertyDescriptors",
    category: "introspection",
    severity: "medium",
    description: "Bulk descriptor read.",
  },
  {
    key: "Object.getOwnPropertyNames",
    category: "introspection",
    severity: "medium",
    description: "Enumerates own properties; used to find injected helper props.",
  },
  {
    key: "Object.getPrototypeOf",
    category: "introspection",
    severity: "medium",
    description: "Walks prototype chain — common in webdriver-prototype probes.",
  },
  {
    key: "Object.defineProperty",
    category: "introspection",
    severity: "medium",
    description: "Often appears in BOTH detection (locking properties) and evasion (overriding getters). Presence isn't a tell on its own; descriptor argument shape matters.",
  },
  {
    key: "Reflect.ownKeys",
    category: "introspection",
    severity: "medium",
    description: "Like getOwnPropertyNames + getOwnPropertySymbols.",
  },
  {
    key: "Proxy",
    category: "introspection",
    severity: "medium",
    description: "Proxies are heavily used by stealth shims; detectors test for Proxy traces (e.g., toString of trapped functions).",
  },
  {
    key: "Symbol.toPrimitive",
    category: "introspection",
    severity: "info",
    description: "Used in deep type-coercion probes.",
  },
  {
    key: "*.constructor",
    category: "introspection",
    severity: "low",
    description: "Walks back to a function from an instance. Check `obj.constructor.name` for class name.",
  },
  {
    key: "*.__proto__",
    category: "introspection",
    severity: "medium",
    description: "Direct prototype access. Often paired with webdriver detection.",
  },
  {
    key: "Error.captureStackTrace",
    category: "introspection",
    severity: "medium",
    description: "V8-specific. Stack-trace contents leak the engine and frame names.",
  },
  {
    key: "Error.prepareStackTrace",
    category: "introspection",
    severity: "high",
    botDetectionTell: true,
    layer: "L3",
    description: "V8 hook for structured stack traces. Some detectors install one to inspect call sites and detect Puppeteer/Playwright glue frames.",
    evasion: "Patch unconditionally on every Error before any detector runs.",
  },
  {
    key: "Reflect.get",
    category: "introspection",
    severity: "medium",
    layer: "L2",
    description: "Indirect property read. Stealth-bypass technique used by detectors to dodge Object.defineProperty-style getter overrides on common APIs.",
    botDetectionTell: true,
  },
  {
    key: "Reflect.getOwnPropertyDescriptor",
    category: "introspection",
    severity: "medium",
    description: "Same descriptor read as Object.getOwnPropertyDescriptor; alternative entry point.",
  },
  {
    key: "Reflect.has",
    category: "introspection",
    severity: "low",
    description: "in-operator equivalent. Rarely fingerprint-load-bearing on its own.",
  },
  {
    key: "Reflect.setPrototypeOf",
    category: "introspection",
    severity: "medium",
    description: "Used alongside Proxy in anti-fp shim detection.",
  },
  {
    key: "Reflect.getPrototypeOf",
    category: "introspection",
    severity: "medium",
    description: "Prototype walk via Reflect; same axis as Object.getPrototypeOf.",
  },
  {
    key: "Reflect.deleteProperty",
    category: "introspection",
    severity: "low",
    description: "Property removal probe — used to check whether a property is [[Configurable]].",
  },
  {
    key: "Object.setPrototypeOf",
    category: "introspection",
    severity: "medium",
    description: "Prototype reassignment. Stealth shims sometimes use this; detectors probe for traces.",
  },
  {
    key: "Object.create",
    category: "introspection",
    severity: "low",
    description: "Object factory. Used in lie-detection cycles (Object.create with cyclic prototype to trigger engine-specific TypeError).",
  },
  {
    key: "*.hasOwnProperty",
    category: "introspection",
    severity: "low",
    description: "Standard property probe. Slightly elevated because lie-detection scripts use it to test that webdriver/permissions properties exist on the right object.",
  },
  {
    key: "Symbol.hasInstance",
    category: "introspection",
    severity: "medium",
    description: "Custom instanceof hook. Trapped Proxies that expose Symbol.hasInstance trip lie-detection.",
  },
  {
    key: "Symbol.iterator",
    category: "introspection",
    severity: "info",
    description: "Iterator protocol; rarely the focus.",
  },
  {
    key: "Symbol.asyncIterator",
    category: "introspection",
    severity: "info",
    description: "Async iterator protocol; rarely the focus.",
  },
  {
    key: "Symbol.toStringTag",
    category: "introspection",
    severity: "medium",
    description: "Class brand tag. Detectors check `Object.prototype.toString.call(navigator.permissions)` returns '[object Permissions]'; tampered prototypes leak the tag.",
  },
  {
    key: "eval.toString",
    category: "introspection",
    severity: "high",
    botDetectionTell: true,
    layer: "L2",
    description: "`eval.toString().length` is a stable engine signature: 33 on V8, 37 on SpiderMonkey, 37 on JSC. Spoofed-UA detection compares this with the claimed browser engine.",
    evasion: "Override Function.prototype.toString globally; ensure eval still passes the [native code] regex AND returns the expected length.",
  },
  {
    key: "*.__lookupSetter__",
    category: "introspection",
    severity: "high",
    botDetectionTell: true,
    layer: "L2",
    description: "Legacy setter introspection. Shape Shifter and other anti-anti-fp tools use `Object.__lookupSetter__('foo').toString()` to detect monkey-patched setters that Object.getOwnPropertyDescriptor might miss.",
  },
  {
    key: "*.__lookupGetter__",
    category: "introspection",
    severity: "high",
    botDetectionTell: true,
    layer: "L2",
    description: "Legacy getter introspection. Same anti-stealth role.",
  },
  {
    key: "*.toString.toString",
    category: "introspection",
    severity: "high",
    botDetectionTell: true,
    layer: "L2",
    description: "Double-toString trick to defeat naïve Function.prototype.toString patches. If the override of toString itself isn't shadowed, this returns the patched source — strong tell for AntiDetect-style wrappers.",
  },
  {
    key: "*.stack",
    category: "introspection",
    severity: "high",
    botDetectionTell: true,
    layer: "L3",
    description: "Stack-trace text read (typically `new Error().stack` or `e.stack` in a catch). Detectors regex this for framework-glue frames: `__puppeteer_evaluation_script__`, `pptr://`, `playwright`, `chrome-extension://`, anonymous frames matching CDP's evaluate pattern. Pair with `Error.prepareStackTrace` for V8-only structured access.",
    evasion: "Wrap the global Error and override .stack getters to a sanitized native-shaped string; mask glue frames before any detector code runs.",
  },
  {
    key: "Function.prototype.bind",
    category: "introspection",
    severity: "medium",
    description: "Bind on Function.prototype. Often paired with .toString to verify a bound function still serializes as native code — stealth wrappers that forget to mask the bound-version source are caught here.",
  },
  {
    key: "Function.prototype.call",
    category: "introspection",
    severity: "medium",
    description: "Function.prototype.call. Common in indirect-invocation introspection probes (`Function.prototype.call.toString()` length check).",
  },
  {
    key: "Function.prototype.apply",
    category: "introspection",
    severity: "medium",
    description: "Function.prototype.apply. Same axis as .call.",
  },
  {
    key: "Function.toString",
    category: "introspection",
    severity: "high",
    botDetectionTell: true,
    layer: "L2",
    description: "`Function.toString.call(victim)` is the classic stealth-bypass trampoline: it sidesteps a patched `Function.prototype.toString` by calling the constructor's own .toString directly. If a wrapper masks the prototype but not Function itself, this returns the unmasked source.",
  },
  {
    key: "*.constructor.toString",
    category: "introspection",
    severity: "high",
    botDetectionTell: true,
    layer: "L2",
    description: "Variant of the constructor-trampoline: `(navigator.permissions.query).constructor.toString.call(victim)` reaches Function.prototype.toString through the constructor chain. Catches patches that only shadow Function.prototype.",
  },
  {
    key: "Error.stackTraceLimit",
    category: "introspection",
    severity: "medium",
    description: "V8-specific stack-trace depth cap. Reads/writes here are usually scaffolding for a deeper stack probe — flag for context.",
  },
];
