import type { ApiDefinition } from "./types.js";

export const webglApis: ApiDefinition[] = [
  {
    key: "*.getContext",
    argMatch: ["webgl", "experimental-webgl", "webgl2", "webgpu"],
    category: "webgl",
    severity: "high",
    botDetectionTell: true,
    description: "Acquires a WebGL/WebGPU context — gateway for GPU fingerprinting.",
    evasion: "Hooking the context return is detectable. Better: patch getParameter and getExtension on the prototype to return a consistent persona.",
  },
  {
    key: "*.getParameter",
    category: "webgl",
    severity: "high",
    botDetectionTell: true,
    layer: "L1a",
    description: "Reads named parameters from a WebGL context. Heavily used for VENDOR/RENDERER + many capability ints.",
    evasion: "Override WebGLRenderingContext.prototype.getParameter for the unmasked-renderer enum (37446) and unmasked-vendor (37445). Be careful not to break legitimate capability queries that detectors also issue.",
  },
  {
    key: "*.getExtension",
    argMatch: ["WEBGL_debug_renderer_info"],
    category: "webgl",
    severity: "high",
    botDetectionTell: true,
    layer: "L1a",
    description: "Requests the debug-renderer-info extension which unlocks UNMASKED_VENDOR_WEBGL (37445) and UNMASKED_RENDERER_WEBGL (37446) — the GPU model string.",
    evasion: "Returning null breaks fingerprinting but the absence is itself anomalous; match real Chrome behaviour and serve a plausible vendor/renderer pair.",
  },
  {
    key: "*.getExtension",
    category: "webgl",
    severity: "medium",
    description: "General extension query. Detectors also enumerate via getSupportedExtensions().",
  },
  {
    key: "*.getSupportedExtensions",
    category: "webgl",
    severity: "high",
    botDetectionTell: true,
    description: "Returns the list of WebGL extensions the GPU/driver supports — high-entropy fingerprint axis.",
  },
  {
    key: "*.getShaderPrecisionFormat",
    category: "webgl",
    severity: "medium",
    description: "Returns precision range/precision for shader types. Stable per GPU.",
  },
  {
    key: "*.getContextAttributes",
    category: "webgl",
    severity: "low",
    description: "Returns the attributes the context was created with.",
  },
  {
    key: "*.readPixels",
    category: "webgl",
    severity: "high",
    botDetectionTell: true,
    description: "Reads pixels back from a rendered scene — used to fingerprint shader output.",
  },
  {
    key: "*.shaderSource",
    category: "webgl",
    severity: "medium",
    description: "Uploads GLSL source. Appearance of long shader source near readPixels indicates a render-output fingerprint (DRAWNAPART-style probes).",
  },
  {
    key: "*.compileShader",
    category: "webgl",
    severity: "medium",
    description: "Compiles a shader. Common in GPU-fingerprint pipelines.",
  },
  {
    key: "*.linkProgram",
    category: "webgl",
    severity: "low",
    description: "Links a shader program. Step in WebGL fingerprint setup.",
  },
  {
    key: "*.useProgram",
    category: "webgl",
    severity: "low",
    description: "Activates a linked program.",
  },
  {
    key: "*.drawArrays",
    category: "webgl",
    severity: "medium",
    description: "Issues a draw call. Paired with readPixels to extract GPU output for fingerprinting.",
  },
  {
    key: "*.drawElements",
    category: "webgl",
    severity: "medium",
    description: "Indexed draw call; same fingerprint role as drawArrays.",
  },
  {
    key: "*.bufferData",
    category: "webgl",
    severity: "info",
    description: "Uploads vertex/index data; standard WebGL setup.",
  },
  {
    key: "*.bindBuffer",
    category: "webgl",
    severity: "info",
    description: "Binds a buffer.",
  },
  {
    key: "*.createShader",
    category: "webgl",
    severity: "low",
    description: "Allocates a shader object.",
  },
  {
    key: "*.createProgram",
    category: "webgl",
    severity: "low",
    description: "Allocates a program object.",
  },
  {
    key: "*.getAttribLocation",
    category: "webgl",
    severity: "info",
    description: "Resolves attribute index.",
  },
  {
    key: "*.getUniformLocation",
    category: "webgl",
    severity: "info",
    description: "Resolves uniform location.",
  },
  {
    key: "*.vertexAttribPointer",
    category: "webgl",
    severity: "info",
    description: "Vertex attribute setup.",
  },
  {
    key: "*.viewport",
    category: "webgl",
    severity: "info",
    description: "WebGL viewport set; appears in fingerprint render setup.",
  },
  {
    key: "*.getExtension",
    argMatch: ["EXT_disjoint_timer_query", "EXT_disjoint_timer_query_webgl2"],
    category: "webgl",
    severity: "high",
    botDetectionTell: true,
    description: "Disjoint Timer Query extension. Unlocks gl.createQuery / beginQuery / endQuery / getQueryParameter for GPU-side nanosecond timing — the DRAWNAPART (2022) attack uses this to fingerprint GPU stalls below the WebGL renderer string.",
    evasion: "Either disable the extension (return null from getExtension) or randomize query results — but absence on a Chrome desktop UA is itself a tell.",
  },
  {
    key: "*.getExtension",
    argMatch: ["ANGLE_instanced_arrays"],
    category: "webgl",
    severity: "medium",
    description: "Required by DRAWNAPART; presence reveals ANGLE wrapper (Windows Chrome).",
  },
  {
    key: "*.getExtension",
    argMatch: ["WEBGL_compressed_texture_s3tc", "WEBGL_compressed_texture_etc", "WEBGL_compressed_texture_astc", "WEBGL_compressed_texture_pvrtc"],
    category: "webgl",
    severity: "medium",
    description: "Compressed-texture extension probe. Set varies by GPU class (mobile/desktop, NVIDIA/AMD/Intel/Mali/Adreno).",
  },
  {
    key: "*.createQuery",
    category: "webgl",
    severity: "high",
    botDetectionTell: true,
    description: "WebGL2 Query object; with TIME_ELAPSED_EXT counts GPU nanoseconds. Core primitive in DRAWNAPART-style timing fingerprints.",
  },
  {
    key: "*.beginQuery",
    category: "webgl",
    severity: "high",
    botDetectionTell: true,
    description: "Starts a timer query — DRAWNAPART pattern.",
  },
  {
    key: "*.endQuery",
    category: "webgl",
    severity: "high",
    botDetectionTell: true,
    description: "Ends a timer query — DRAWNAPART pattern.",
  },
  {
    key: "*.getQueryParameter",
    category: "webgl",
    severity: "high",
    botDetectionTell: true,
    description: "Reads QUERY_RESULT — GPU-side nanosecond timing exfiltrated to a fingerprint.",
  },
  {
    key: "*.uniform1i",
    category: "webgl",
    severity: "info",
    description: "Integer uniform set. Appears en-masse in DRAWNAPART pattern (per-iteration uniform updates).",
  },
  {
    key: "*.createTransformFeedback",
    category: "webgl",
    severity: "medium",
    description: "WebGL2 transform feedback. Captures vertex-shader output without rendering — alternate fingerprint-extraction path.",
  },
  {
    key: "*.beginTransformFeedback",
    category: "webgl",
    severity: "medium",
    description: "Begins transform-feedback capture.",
  },
];
