import type { ApiDefinition } from "../types.js";

export const audioApis: ApiDefinition[] = [
  {
    key: "AudioContext",
    category: "audio",
    severity: "high",
    botDetectionTell: true,
    layer: "L1a",
    description: "Web Audio API entry point. Combined with OfflineAudioContext for the canonical audio fingerprint.",
    evasion: "Hook AnalyserNode.getFloatFrequencyData / getChannelData to add per-session noise. Pure interception is detectable; perturbation preserves API shape.",
  },
  {
    key: "OfflineAudioContext",
    category: "audio",
    severity: "high",
    botDetectionTell: true,
    layer: "L1a",
    description: "Renders audio offline at full speed. Standard fingerprinting recipe: oscillator → compressor → render → hash output buffer.",
  },
  {
    key: "webkitAudioContext",
    category: "audio",
    severity: "high",
    botDetectionTell: true,
    description: "Legacy prefixed AudioContext — detectors often probe both.",
  },
  {
    key: "*.createOscillator",
    category: "audio",
    severity: "medium",
    description: "Creates an OscillatorNode — the source signal in audio fingerprinting.",
  },
  {
    key: "*.createDynamicsCompressor",
    category: "audio",
    severity: "high",
    botDetectionTell: true,
    description: "DynamicsCompressorNode — its quirky DSP behaviour across CPU/OS combinations is the entropy source.",
  },
  {
    key: "*.createAnalyser",
    category: "audio",
    severity: "medium",
    description: "AnalyserNode for frequency/time-domain reads.",
  },
  {
    key: "*.getChannelData",
    category: "audio",
    severity: "high",
    botDetectionTell: true,
    description: "Reads raw PCM samples — the read-side of the audio fingerprint pipeline.",
  },
  {
    key: "*.getFloatFrequencyData",
    category: "audio",
    severity: "medium",
    description: "Spectral output read; alternative read sink.",
  },
  {
    key: "*.startRendering",
    category: "audio",
    severity: "high",
    botDetectionTell: true,
    description: "OfflineAudioContext.startRendering — kicks off the offline render whose output is hashed.",
  },
  {
    key: "*.createBiquadFilter",
    category: "audio",
    severity: "medium",
    description: "BiquadFilterNode. Default values (frequency.defaultValue, Q.defaultValue, gain.maxValue) are stable per-engine and form an audio-fingerprint axis.",
  },
  {
    key: "*.createGain",
    category: "audio",
    severity: "info",
    description: "GainNode constructor.",
  },
  {
    key: "*.createBufferSource",
    category: "audio",
    severity: "low",
    description: "AudioBufferSourceNode; alternative signal source.",
  },
  {
    key: "*.createScriptProcessor",
    category: "audio",
    severity: "low",
    description: "ScriptProcessorNode — deprecated but still functional for per-sample fingerprinting.",
  },
  {
    key: "*.getByteFrequencyData",
    category: "audio",
    severity: "medium",
    description: "AnalyserNode.getByteFrequencyData — alternative spectral read.",
  },
  {
    key: "*.getByteTimeDomainData",
    category: "audio",
    severity: "medium",
    description: "AnalyserNode.getByteTimeDomainData — time-domain read.",
  },
  {
    key: "*.getFloatTimeDomainData",
    category: "audio",
    severity: "medium",
    description: "AnalyserNode.getFloatTimeDomainData — float time-domain read.",
  },
  {
    key: "*.copyFromChannel",
    category: "audio",
    severity: "high",
    botDetectionTell: true,
    description: "AudioBuffer.copyFromChannel. Alternative pixel-equivalent read for audio buffer; stealth shims patching getChannelData often forget this path.",
  },
  {
    key: "*.copyToChannel",
    category: "audio",
    severity: "medium",
    description: "AudioBuffer.copyToChannel; less common but still fingerprint-relevant.",
  },
  {
    key: "*.baseLatency",
    category: "audio",
    severity: "high",
    botDetectionTell: true,
    description: "AudioContext.baseLatency. Float that depends on the OS audio stack (e.g. 0.01160997… on Linux/44.1kHz). Strong OS-fingerprint axis used by 2022 AudioContext Browser Fingerprinting.",
  },
  {
    key: "*.outputLatency",
    category: "audio",
    severity: "medium",
    description: "AudioContext.outputLatency. Nonzero on hardware contexts; 0 on offline. Helps separate live-audio from offline fingerprint paths.",
  },
  {
    key: "*.sampleRate",
    category: "audio",
    severity: "medium",
    description: "AudioContext.sampleRate. 44100 on Linux defaults, 48000 on macOS — coarse OS hint.",
  },
  {
    key: "*.maxChannelCount",
    category: "audio",
    severity: "medium",
    description: "AudioContext.destination.maxChannelCount. 2/6/8 distinguishes stereo / 5.1 / 7.1 audio hardware.",
  },
  {
    key: "AudioWorklet",
    category: "audio",
    severity: "low",
    description: "Modern audio-processing worklet; presence pins Chrome 66+.",
  },
  {
    key: "AudioWorkletNode",
    category: "audio",
    severity: "low",
    description: "AudioWorklet node constructor.",
  },
  {
    key: "*.addModule",
    category: "audio",
    severity: "low",
    description: "AudioWorklet.addModule(). Used to load a custom AudioWorkletProcessor; processing latency leaks CPU class.",
  },
];
