import type { ApiDefinition } from "../types.js";

export const eventsDomApis: ApiDefinition[] = [
  {
    key: "*.addEventListener",
    category: "events",
    severity: "info",
    description: "Generic listener install. Fingerprint-relevant when the event name is 'mousemove', 'mousedown', 'pointermove', 'devicemotion', or 'deviceorientation' — used to score human-like input.",
    evasion: "If you detect synthetic input, generate plausibly noisy mouse paths and dispatch via CDP Input.dispatchMouseEvent (untrusted) or via real OS-level injection (trusted) before the page loads its handlers.",
  },
  {
    key: "*.dispatchEvent",
    category: "events",
    severity: "low",
    description: "Synthetic event dispatch. Detectors check `event.isTrusted` — synthetic events are flagged.",
  },
  {
    key: "*.getBoundingClientRect",
    category: "dom-layout",
    severity: "medium",
    description: "Geometry probe. Sub-pixel rect values vary across font-stack/zoom/DPR combinations and are stable per environment.",
  },
  {
    key: "*.getClientRects",
    category: "dom-layout",
    severity: "medium",
    description: "Multi-rect geometry probe; same fingerprint axis as getBoundingClientRect.",
  },
  {
    key: "MutationObserver",
    category: "dom-layout",
    severity: "info",
    description: "Used both by detectors (to spot late DOM tampering) and by stealth shims (to re-apply patches).",
  },
  {
    key: "matchMedia",
    category: "dom-layout",
    severity: "low",
    description: "Media-query probes. `(prefers-color-scheme)`, `(prefers-reduced-motion)`, `(forced-colors)`, `(any-pointer)`, `(hover)` all add fingerprint entropy.",
  },
  {
    key: "IntersectionObserver",
    category: "dom-layout",
    severity: "info",
    description: "Constructor capability probe.",
  },
  {
    key: "ResizeObserver",
    category: "dom-layout",
    severity: "info",
    description: "Constructor capability probe.",
  },
  {
    key: "PerformanceObserver",
    category: "dom-layout",
    severity: "info",
    description: "Constructor capability probe — paired with observe('longtask', 'paint', 'measure').",
  },
  {
    key: "ReportingObserver",
    category: "dom-layout",
    severity: "low",
    description: "Brave-resistance fingerprint axis (Brave / Tor return null for new ReportingObserver options).",
  },
  {
    key: "*.observe",
    category: "dom-layout",
    severity: "info",
    description: "Generic .observe() call; alone not meaningful, but co-occurrence with PerformanceObserver near timing fingerprints is.",
  },
  {
    key: "*.isTrusted",
    category: "events",
    severity: "high",
    botDetectionTell: true,
    description: "Event.isTrusted. Synthetic events dispatched via dispatchEvent or CDP Input.dispatchMouseEvent (without untrusted=false) read as false — direct automation tell.",
    evasion: "Real OS-level input injection or CDP with proper trusted-context flags. Hooking isTrusted requires patching Event.prototype getters.",
  },
  {
    key: "*.movementX",
    category: "events",
    severity: "medium",
    description: "MouseEvent.movementX. Distribution of mouse-movement deltas; bots produce straight-line / constant-velocity tracks that classifiers separate from human noise.",
    botDetectionTell: true,
  },
  {
    key: "*.movementY",
    category: "events",
    severity: "medium",
    description: "MouseEvent.movementY.",
  },
  {
    key: "*.pressure",
    category: "events",
    severity: "medium",
    description: "PointerEvent.pressure. Touch/pen events should report sub-1 values; mouse always 0.5. Constant or NaN under headless automation.",
    botDetectionTell: true,
  },
  {
    key: "*.tangentialPressure",
    category: "events",
    severity: "low",
    description: "PointerEvent.tangentialPressure. Always 0 unless a real pen is in use.",
  },
  {
    key: "*.tiltX",
    category: "events",
    severity: "low",
    description: "PointerEvent.tiltX. Pen tilt; 0 unless real input.",
  },
  {
    key: "*.tiltY",
    category: "events",
    severity: "low",
    description: "PointerEvent.tiltY.",
  },
  {
    key: "*.timeStamp",
    category: "events",
    severity: "low",
    description: "Event.timeStamp. Inter-event delta histogram — bots produce uniform deltas, humans don't.",
  },
  {
    key: "*.elementFromPoint",
    category: "dom-layout",
    severity: "medium",
    description: "document.elementFromPoint(x,y). Honeypot-link probing: detectors hide an invisible anchor at known coords; if elementFromPoint returns it AND a click event ever fires on it, the visitor is a bot.",
    botDetectionTell: true,
  },
  {
    key: "*.elementsFromPoint",
    category: "dom-layout",
    severity: "low",
    description: "document.elementsFromPoint(x,y). Same honeypot vector as elementFromPoint.",
  },
];
