import type { ApiDefinition } from "../types.js";

/**
 * Properties whose mere presence (or absence) on the global has
 * historically been used to identify automation frameworks. Independent
 * of category-organized fingerprint surfaces because these are rarely
 * checked for value — only existence.
 */
export const headlessTellApis: ApiDefinition[] = [
  {
    key: "callPhantom",
    category: "headless-tells",
    severity: "high",
    botDetectionTell: true,
    description: "PhantomJS bridge function. Existence on `window` proves PhantomJS.",
  },
  {
    key: "_phantom",
    category: "headless-tells",
    severity: "high",
    botDetectionTell: true,
    description: "PhantomJS internal handle.",
  },
  {
    key: "phantom",
    category: "headless-tells",
    severity: "high",
    botDetectionTell: true,
    description: "Older PhantomJS marker.",
  },
  {
    key: "Buffer",
    category: "headless-tells",
    severity: "high",
    botDetectionTell: true,
    description: "Node.js Buffer leaking into a 'browser' context — signals a Node-based driver (Electron, NW.js, Nightmare).",
  },
  {
    key: "emit",
    category: "headless-tells",
    severity: "medium",
    botDetectionTell: true,
    description: "EventEmitter-style global; classic Nightmare/Electron leak.",
  },
  {
    key: "spawn",
    category: "headless-tells",
    severity: "medium",
    botDetectionTell: true,
    description: "Node child_process leak.",
  },
  {
    key: "domAutomation",
    category: "headless-tells",
    severity: "high",
    botDetectionTell: true,
    description: "Chrome --enable-automation injects this. Direct tell.",
  },
  {
    key: "domAutomationController",
    category: "headless-tells",
    severity: "high",
    botDetectionTell: true,
    description: "Chrome --enable-automation injects this. Direct tell.",
  },
  {
    key: "__nightmare",
    category: "headless-tells",
    severity: "high",
    botDetectionTell: true,
    description: "Nightmare.js bridge.",
  },
  {
    key: "__selenium_unwrapped",
    category: "headless-tells",
    severity: "high",
    botDetectionTell: true,
    description: "Selenium IDE marker.",
  },
  {
    key: "__webdriver_evaluate",
    category: "headless-tells",
    severity: "high",
    botDetectionTell: true,
    description: "Selenium internal property.",
  },
  {
    key: "__driver_evaluate",
    category: "headless-tells",
    severity: "high",
    botDetectionTell: true,
    description: "Selenium internal property.",
  },
  {
    key: "__webdriver_script_function",
    category: "headless-tells",
    severity: "high",
    botDetectionTell: true,
    description: "Selenium injected helper.",
  },
  {
    key: "__webdriver_script_func",
    category: "headless-tells",
    severity: "high",
    botDetectionTell: true,
    description: "Selenium injected helper.",
  },
  {
    key: "__webdriver_script_fn",
    category: "headless-tells",
    severity: "high",
    botDetectionTell: true,
    description: "Selenium injected helper.",
  },
  {
    key: "__fxdriver_evaluate",
    category: "headless-tells",
    severity: "high",
    botDetectionTell: true,
    description: "Firefox driver helper.",
  },
  {
    key: "__driver_unwrapped",
    category: "headless-tells",
    severity: "high",
    botDetectionTell: true,
    description: "Selenium driver-unwrapped marker.",
  },
  {
    key: "__webdriver_unwrapped",
    category: "headless-tells",
    severity: "high",
    botDetectionTell: true,
    description: "Selenium driver-unwrapped marker.",
  },
  {
    key: "__selenium_evaluate",
    category: "headless-tells",
    severity: "high",
    botDetectionTell: true,
    description: "Selenium evaluator helper.",
  },
  {
    key: "__fxdriver_unwrapped",
    category: "headless-tells",
    severity: "high",
    botDetectionTell: true,
    description: "Firefox driver helper.",
  },
  {
    key: "$cdc_asdjflasutopfhvcZLmcfl_",
    category: "headless-tells",
    severity: "high",
    botDetectionTell: true,
    description: "ChromeDriver injects this property on document. The exact name is hardcoded in chromedriver.exe binaries; patching the binary is one mitigation.",
    evasion: "Patch chromedriver binary to use a different name, or use undetected-chromedriver / rebrowser.",
  },
  {
    key: "$chrome_asyncScriptInfo",
    category: "headless-tells",
    severity: "high",
    botDetectionTell: true,
    description: "ChromeDriver async-script bridge marker.",
  },
  {
    key: "cdc_adoQpoasnfa76pfcZLmcfl_Array",
    category: "headless-tells",
    severity: "high",
    botDetectionTell: true,
    description: "ChromeDriver-injected sentinel; same family as $cdc_.",
  },
  {
    key: "cdc_adoQpoasnfa76pfcZLmcfl_Promise",
    category: "headless-tells",
    severity: "high",
    botDetectionTell: true,
    description: "ChromeDriver-injected sentinel.",
  },
  {
    key: "cdc_adoQpoasnfa76pfcZLmcfl_Symbol",
    category: "headless-tells",
    severity: "high",
    botDetectionTell: true,
    description: "ChromeDriver-injected sentinel.",
  },
  {
    key: "navigator.__proto__.webdriver",
    category: "headless-tells",
    severity: "high",
    botDetectionTell: true,
    description: "Probes the prototype chain to bypass instance-level shims.",
    evasion: "Override on Navigator.prototype, not on the navigator instance, so prototype-walks see the patched value.",
  },
  {
    key: "__playwright__binding__",
    category: "headless-tells",
    severity: "high",
    botDetectionTell: true,
    description: "Playwright binding marker injected into pages with exposed bindings.",
  },
  {
    key: "__pwInitScripts",
    category: "headless-tells",
    severity: "high",
    botDetectionTell: true,
    description: "Playwright init-script bookkeeping global.",
  },
  {
    key: "__puppeteer_evaluation_script__",
    category: "headless-tells",
    severity: "high",
    botDetectionTell: true,
    description: "Puppeteer source-name marker in stack traces.",
  },
  {
    key: "_selenium",
    category: "headless-tells",
    severity: "high",
    botDetectionTell: true,
    description: "Selenium-IDE injected sentinel.",
  },
  {
    key: "_Selenium_IDE_Recorder",
    category: "headless-tells",
    severity: "high",
    botDetectionTell: true,
    description: "Selenium-IDE recorder marker.",
  },
  {
    key: "Selenium",
    category: "headless-tells",
    severity: "high",
    botDetectionTell: true,
    description: "Selenium browser-driver capitalized marker.",
  },
  {
    key: "webdriver",
    category: "headless-tells",
    severity: "high",
    botDetectionTell: true,
    description: "Bare `webdriver` global on `window` — appears in some configurations beyond the navigator property.",
  },
  {
    key: "process",
    category: "headless-tells",
    severity: "high",
    botDetectionTell: true,
    description: "Node-process global leaking into a browser realm (Electron, NW.js, jsdom).",
  },
  {
    key: "require",
    category: "headless-tells",
    severity: "high",
    botDetectionTell: true,
    description: "Node `require` leaking into a browser realm.",
  },
  {
    key: "module",
    category: "headless-tells",
    severity: "medium",
    botDetectionTell: true,
    description: "Node `module` leaking; weaker signal because some bundlers create it intentionally.",
  },
  {
    key: "global",
    category: "headless-tells",
    severity: "medium",
    botDetectionTell: true,
    description: "Node `global` leaking. Often paired with `process` checks.",
  },
  {
    key: "Window.prototype.outerHeight",
    category: "headless-tells",
    severity: "high",
    botDetectionTell: true,
    description: "Reading outerHeight on the prototype side-steps instance-level overrides; 0 confirms headless.",
  },
];
