import type { ApiDefinition } from "../types.js";

export const navigatorApis: ApiDefinition[] = [
  {
    key: "navigator.userAgent",
    category: "navigator",
    severity: "low",
    description: "Browser-supplied UA string. The single most-checked fingerprint surface.",
    evasion: "Trivially overridable via Object.defineProperty(navigator, 'userAgent', { get: () => '...' }) or CDP Network.setUserAgentOverride. Detectors counter by cross-checking with userAgentData and feature inference.",
  },
  {
    key: "navigator.userAgentData",
    category: "navigator",
    severity: "medium",
    description: "Structured Client Hints. Newer than userAgent; many spoofers forget to override it, creating a tell.",
    evasion: "Override .brands, .mobile, .platform, and .getHighEntropyValues() returning consistent values with userAgent.",
  },
  {
    key: "navigator.webdriver",
    category: "navigator",
    severity: "high",
    botDetectionTell: true,
    description: "Standardized boolean that is `true` whenever the browser is driven by WebDriver/CDP. Hard signal of automation.",
    evasion: "Patched at runtime via `Object.defineProperty(navigator, 'webdriver', {get: () => false})` injected pre-document-load with --disable-blink-features=AutomationControlled, or use rebrowser/puppeteer-stealth.",
  },
  {
    key: "navigator.plugins",
    category: "navigator",
    severity: "medium",
    botDetectionTell: true,
    description: "Plugin list. Headless Chrome has zero by default; legitimate Chrome reports PDF Viewer entries. Empty list is a tell.",
    evasion: "Polyfill plugins to match a non-headless Chrome (Chrome PDF Plugin, Chrome PDF Viewer, Native Client) and ensure .length, indexed access, and namedItem all behave.",
  },
  {
    key: "navigator.mimeTypes",
    category: "navigator",
    severity: "medium",
    description: "Companion to plugins; checked together for consistency.",
    evasion: "Spoof alongside plugins; the two arrays are linked by .enabledPlugin references.",
  },
  {
    key: "navigator.languages",
    category: "navigator",
    severity: "medium",
    botDetectionTell: true,
    description: "Locale preference array. Empty array (length 0) was a long-standing headless tell. Mismatch with Accept-Language header is also flagged.",
    evasion: "Set via launch flag --lang or override the getter; ensure it matches Accept-Language and navigator.language.",
  },
  {
    key: "navigator.language",
    category: "navigator",
    severity: "low",
    description: "Primary locale. Cross-checked against languages[0], Intl, and Accept-Language.",
  },
  {
    key: "navigator.hardwareConcurrency",
    category: "navigator",
    severity: "medium",
    description: "Logical CPU count. Combined with deviceMemory and timing micro-benchmarks to fingerprint hardware.",
    evasion: "Override the getter; popular values are 4, 8, 12, 16. Ensure timing benchmarks (run a tight loop, measure) produce consistent results.",
  },
  {
    key: "navigator.deviceMemory",
    category: "navigator",
    severity: "medium",
    description: "Approximate RAM in GB (rounded). Chrome only. Coarse but stable signal.",
    evasion: "Override; common values are 0.25, 0.5, 1, 2, 4, 8.",
  },
  {
    key: "navigator.platform",
    category: "navigator",
    severity: "low",
    description: "OS string (Win32, MacIntel, Linux x86_64). Cross-checked with userAgent.",
  },
  {
    key: "navigator.vendor",
    category: "navigator",
    severity: "low",
    description: "Browser vendor string ('Google Inc.', 'Apple Computer, Inc.', '').",
  },
  {
    key: "navigator.vendorSub",
    category: "navigator",
    severity: "info",
    description: "Almost always empty; used in rare consistency checks.",
  },
  {
    key: "navigator.productSub",
    category: "navigator",
    severity: "low",
    description: "'20030107' on WebKit/Blink, '20100101' on Gecko. A small but exact fingerprint axis.",
  },
  {
    key: "navigator.oscpu",
    category: "navigator",
    severity: "low",
    description: "Firefox-only OS/CPU descriptor; presence on a UA claiming Chrome is a tell.",
    botDetectionTell: true,
  },
  {
    key: "navigator.buildID",
    category: "navigator",
    severity: "low",
    description: "Firefox build ID; presence outside Firefox is suspicious.",
  },
  {
    key: "navigator.doNotTrack",
    category: "navigator",
    severity: "low",
    description: "User DNT preference ('1', '0', null, 'unspecified'). Adds entropy.",
  },
  {
    key: "navigator.cookieEnabled",
    category: "navigator",
    severity: "info",
    description: "Boolean; near-universally true in real browsers.",
  },
  {
    key: "navigator.onLine",
    category: "navigator",
    severity: "info",
    description: "Network connectivity hint.",
  },
  {
    key: "navigator.maxTouchPoints",
    category: "navigator",
    severity: "medium",
    description: "Touch capability. Headless Chrome on Linux reports 0 even when UA claims mobile — strong inconsistency tell.",
    botDetectionTell: true,
    evasion: "Override consistently with platform/UA; spoof TouchEvent presence too.",
  },
  {
    key: "navigator.pdfViewerEnabled",
    category: "navigator",
    severity: "low",
    description: "Newer Chrome property; should be true on regular Chrome.",
  },
  {
    key: "navigator.connection",
    category: "navigator",
    severity: "medium",
    description: "NetworkInformation. effectiveType / downlink / rtt are stable per network and used as a fingerprint axis.",
  },
  {
    key: "navigator.permissions",
    category: "navigator",
    severity: "high",
    botDetectionTell: true,
    description: "Permissions API. The `Notification.permission === 'denied' && permissions.query({name:'notifications'}).state === 'prompt'` mismatch is the canonical Chrome-headless detector.",
    evasion: "Patch permissions.query so that when navigator-state is 'denied', the returned PermissionStatus.state is also 'denied'.",
  },
  {
    key: "navigator.serviceWorker",
    category: "navigator",
    severity: "info",
    description: "Service worker registration interface; presence checked for capability.",
  },
  {
    key: "navigator.mediaDevices",
    category: "navigator",
    severity: "medium",
    description: "Media device enumeration. enumerateDevices() returns devices' deviceId/label — strong fingerprint axis.",
  },
  {
    key: "navigator.getBattery",
    category: "navigator",
    severity: "medium",
    description: "Battery API (deprecated in many browsers). Charging state, level, and discharge time form a transient fingerprint.",
  },
  {
    key: "navigator.getGamepads",
    category: "navigator",
    severity: "low",
    description: "Gamepad enumeration; mostly checked for capability presence.",
  },
  {
    key: "navigator.getInstalledRelatedApps",
    category: "navigator",
    severity: "info",
    description: "PWA-related; rarely used for detection.",
  },
  {
    key: "navigator.bluetooth",
    category: "navigator",
    severity: "low",
    description: "Bluetooth API capability check.",
  },
  {
    key: "navigator.usb",
    category: "navigator",
    severity: "low",
    description: "WebUSB capability check.",
  },
  {
    key: "navigator.gpu",
    category: "navigator",
    severity: "medium",
    description: "WebGPU. Adapter info exposes high-resolution GPU model strings.",
  },
  {
    key: "navigator.storage",
    category: "navigator",
    severity: "low",
    description: "StorageManager. estimate() leaks rough disk quota.",
  },
  {
    key: "navigator.presentation",
    category: "navigator",
    severity: "info",
    description: "Presentation API; rarely fingerprinted.",
  },
  {
    key: "navigator.appVersion",
    category: "navigator",
    severity: "low",
    description: "Legacy UA companion. Detectors cross-check appVersion against userAgent — they normally only differ in the leading 'Mozilla/'.",
    botDetectionTell: true,
  },
  {
    key: "navigator.appName",
    category: "navigator",
    severity: "low",
    description: "Always 'Netscape' on real browsers — anomaly is a tell.",
  },
  {
    key: "navigator.appCodeName",
    category: "navigator",
    severity: "info",
    description: "Always 'Mozilla' on real browsers.",
  },
  {
    key: "navigator.product",
    category: "navigator",
    severity: "info",
    description: "Always 'Gecko' on real browsers.",
  },
  {
    key: "navigator.globalPrivacyControl",
    category: "navigator",
    severity: "low",
    description: "GPC signal (true/false/undefined). Adds a small fingerprint axis tied to user privacy settings.",
  },
  {
    key: "navigator.brave",
    category: "navigator",
    severity: "high",
    botDetectionTell: true,
    description: "Brave-only namespace. brave.isBrave() / brave.getBraveMode() identify Brave even when UA mimics Chrome. Common evasion target.",
    evasion: "Brave-spoofing requires either deleting `navigator.brave` (which makes the UA inconsistent) or shimming a believable Brave persona.",
  },
  {
    key: "navigator.setAppBadge",
    category: "navigator",
    severity: "info",
    description: "App-badge API capability check; rarely fingerprinted directly.",
  },
  {
    key: "navigator.clearAppBadge",
    category: "navigator",
    severity: "info",
    description: "Companion to setAppBadge.",
  },
  {
    key: "navigator.webkitTemporaryStorage",
    category: "navigator",
    severity: "low",
    description: "Legacy quota API. queryUsageAndQuota leaks disk quota even when navigator.storage is patched.",
    botDetectionTell: true,
  },
  {
    key: "navigator.webkitPersistentStorage",
    category: "navigator",
    severity: "low",
    description: "Legacy persistent-storage quota API; same axis as webkitTemporaryStorage.",
  },
  {
    key: "navigator.mediaCapabilities",
    category: "navigator",
    severity: "medium",
    description: "Entry point for MediaCapabilities.decodingInfo / .encodingInfo. Hardware codec support is a strong fingerprint axis.",
  },
  {
    key: "navigator.userAgentData.brands",
    category: "navigator",
    severity: "medium",
    description: "Brand list (e.g., 'Chromium', 'Google Chrome', 'Not_A Brand'). Mismatch with UA major version is a spoof tell.",
    botDetectionTell: true,
  },
  {
    key: "navigator.userAgentData.mobile",
    category: "navigator",
    severity: "medium",
    description: "Mobile flag. Must be consistent with maxTouchPoints, viewport, and UA.",
  },
  {
    key: "navigator.userAgentData.platform",
    category: "navigator",
    severity: "medium",
    description: "Platform string (e.g., 'macOS', 'Windows'). Cross-checked with navigator.platform and userAgent.",
  },
  {
    key: "navigator.userAgentData.getHighEntropyValues",
    category: "navigator",
    severity: "high",
    botDetectionTell: true,
    description: "Async API for platformVersion / architecture / bitness / model / uaFullVersion / wow64. Strong fingerprint axis; missing or inconsistent results vs UA strings flag spoofs.",
    evasion: "Override on NavigatorUAData.prototype, returning a promise that resolves to values consistent with the spoofed UA major.",
  },
  {
    key: "*.getHighEntropyValues",
    category: "navigator",
    severity: "high",
    botDetectionTell: true,
    description: "Aliased high-entropy probe (var d = navigator.userAgentData; d.getHighEntropyValues()).",
  },
  {
    key: "*.requestAdapter",
    category: "navigator",
    severity: "high",
    botDetectionTell: true,
    description: "navigator.gpu.requestAdapter(). Returns a GPUAdapter whose requestAdapterInfo() leaks vendor/architecture/device — a WebGPU-era replacement for WEBGL_debug_renderer_info.",
  },
  {
    key: "*.requestAdapterInfo",
    category: "navigator",
    severity: "high",
    botDetectionTell: true,
    description: "GPUAdapter.requestAdapterInfo(). High-resolution GPU identity for WebGPU. Hooking this is a frequent gap in stealth toolchains.",
  },
  {
    key: "*.getAvailability",
    category: "navigator",
    severity: "low",
    description: "navigator.bluetooth.getAvailability(). Returns whether a Bluetooth radio is present — a coarse hardware probe.",
  },
  {
    key: "navigator.requestMIDIAccess",
    category: "navigator",
    severity: "medium",
    description: "Web MIDI. Presence and the resolved MIDIAccess.inputs/.outputs list reveal connected MIDI devices.",
  },
  {
    key: "navigator.mediaSession",
    category: "navigator",
    severity: "low",
    description: "Media Session API. Capability probe — Chrome mobile leaning signal.",
  },
  {
    key: "navigator.share",
    category: "navigator",
    severity: "low",
    description: "Web Share API. Mobile-Chrome signal; capability check.",
  },
  {
    key: "navigator.canShare",
    category: "navigator",
    severity: "low",
    description: "Companion to navigator.share.",
  },
  {
    key: "navigator.contacts",
    category: "navigator",
    severity: "low",
    description: "Contacts API (Android Chrome).",
  },
  {
    key: "navigator.virtualKeyboard",
    category: "navigator",
    severity: "low",
    description: "VirtualKeyboard API (Chromium/ChromeOS/Edge).",
  },
  {
    key: "navigator.wakeLock",
    category: "navigator",
    severity: "low",
    description: "WakeLock API. .request('screen') secure-context probe.",
  },
  {
    key: "navigator.serial",
    category: "navigator",
    severity: "low",
    description: "Web Serial (Chromium-only).",
  },
  {
    key: "navigator.hid",
    category: "navigator",
    severity: "low",
    description: "WebHID (Chromium-only).",
  },
  {
    key: "navigator.locks",
    category: "navigator",
    severity: "low",
    description: "Web Locks API.",
  },
  {
    key: "navigator.scheduling",
    category: "navigator",
    severity: "medium",
    description: "Chromium-only navigator.scheduling.isInputPending(). Presence pins Blink.",
    botDetectionTell: true,
  },
  {
    key: "navigator.clipboard",
    category: "navigator",
    severity: "low",
    description: "Clipboard API root. readText/writeText permission-gated; presence/absence and permission state are fingerprint axes.",
  },
  {
    key: "navigator.userActivation",
    category: "navigator",
    severity: "high",
    botDetectionTell: true,
    description: "UserActivation v2. .hasBeenActive and .isActive. False throughout the session = automation that never produced a real user gesture.",
    evasion: "Hard to forge — requires CDP Input.dispatchKeyEvent / dispatchMouseEvent with proper trusted-context flags, or OS-level input injection.",
  },
  {
    key: "*.userActivation",
    category: "navigator",
    severity: "high",
    botDetectionTell: true,
    description: "Aliased userActivation access.",
  },
  {
    key: "*.getDisplayMedia",
    category: "navigator",
    severity: "low",
    description: "navigator.mediaDevices.getDisplayMedia. Desktop-only — absence on a Chrome-desktop UA is a tell.",
    botDetectionTell: true,
  },
  {
    key: "navigator.activeVRDisplays",
    category: "navigator",
    severity: "low",
    description: "Legacy VR enumeration; Firefox-only. Presence reveals engine.",
  },
  {
    key: "navigator.getVRDisplays",
    category: "navigator",
    severity: "low",
    description: "Legacy VR enumeration.",
  },
  {
    key: "navigator.cpuClass",
    category: "navigator",
    severity: "low",
    description: "Legacy IE/Edge surface; presence in modern Chrome would be a spoofer artifact.",
    botDetectionTell: true,
  },
  {
    key: "navigator.sendBeacon",
    category: "navigator",
    severity: "medium",
    description: "Common fingerprint-exfiltration sink used by ebay/microsoft/stackoverflow/washingtonpost trackers (EssentialFP 2020). Listed here because the call signals 'tracker' even when the body is opaque.",
  },
];
