import type { ApiDefinition } from "../types.js";

export const windowScreenApis: ApiDefinition[] = [
  {
    key: "screen.width",
    category: "screen",
    severity: "low",
    description: "Physical display width in CSS pixels.",
  },
  {
    key: "screen.height",
    category: "screen",
    severity: "low",
    description: "Physical display height in CSS pixels.",
  },
  {
    key: "screen.availWidth",
    category: "screen",
    severity: "low",
    description: "Available width minus OS chrome (taskbar, dock).",
  },
  {
    key: "screen.availHeight",
    category: "screen",
    severity: "low",
    description: "Available height minus OS chrome.",
  },
  {
    key: "screen.colorDepth",
    category: "screen",
    severity: "low",
    description: "Almost always 24. Anomalous values (e.g., 48) are headless tells.",
    botDetectionTell: true,
  },
  {
    key: "screen.pixelDepth",
    category: "screen",
    severity: "low",
    description: "Mirrors colorDepth. Mismatch is suspicious.",
  },
  {
    key: "screen.orientation",
    category: "screen",
    severity: "info",
    description: "Orientation type/angle — mostly mobile detection.",
  },

  {
    key: "innerWidth",
    category: "window",
    severity: "low",
    description: "Viewport width. Combined with outer dimensions to detect headless (outer often 0 in headless).",
    botDetectionTell: true,
  },
  {
    key: "innerHeight",
    category: "window",
    severity: "low",
    description: "Viewport height.",
  },
  {
    key: "outerWidth",
    category: "window",
    severity: "medium",
    description: "Window-frame width. 0 in headless Chrome — a very common tell.",
    botDetectionTell: true,
    evasion: "Override to a plausible value (innerWidth + a few px chrome) and keep consistent with screen dimensions.",
  },
  {
    key: "outerHeight",
    category: "window",
    severity: "medium",
    description: "Window-frame height. 0 in headless — common tell.",
    botDetectionTell: true,
  },
  {
    key: "devicePixelRatio",
    category: "window",
    severity: "low",
    description: "DPR; values like 1, 1.25, 1.5, 2, 3 are common. Combined with screen size.",
  },
  {
    key: "window.chrome",
    category: "window",
    severity: "high",
    botDetectionTell: true,
    description: "Real Chrome exposes `window.chrome` with .runtime, .app, .csi, .loadTimes. Headless Chrome historically lacked it; Puppeteer-extra-stealth restores it. Still probed for sub-property correctness.",
    evasion: "Inject a complete `window.chrome` shim (loadTimes returning timing data, csi, runtime); detectors test for specific sub-property descriptors.",
  },
  {
    key: "chrome.runtime",
    category: "window",
    severity: "high",
    botDetectionTell: true,
    description: "Chrome extension runtime. Presence on a non-extension page is normal; absence is a headless tell. Also the entry point for extension-fingerprinting probes via chrome.runtime.sendMessage / .connect against known extension IDs (Carnus 2020).",
  },
  {
    key: "chrome.loadTimes",
    category: "window",
    severity: "high",
    botDetectionTell: true,
    description: "Deprecated but still probed. Calling it should return an object with specific fields.",
  },
  {
    key: "chrome.csi",
    category: "window",
    severity: "high",
    botDetectionTell: true,
    description: "Deprecated client-side instrumentation. Existence is checked.",
  },
  {
    key: "window.opera",
    category: "window",
    severity: "info",
    description: "Legacy Opera detection.",
  },
  {
    key: "history.length",
    category: "window",
    severity: "info",
    description: "Often 1 in fresh automated sessions; non-1 suggests real navigation.",
  },
  {
    key: "location.href",
    category: "window",
    severity: "info",
    description: "Current URL; trivially checked.",
  },
  {
    key: "screen.availLeft",
    category: "screen",
    severity: "low",
    description: "X position of available screen area. Non-zero on macOS (menu bar offset) — used as OS hint.",
  },
  {
    key: "screen.availTop",
    category: "screen",
    severity: "low",
    description: "Y position of available screen area. Non-zero on Windows (taskbar top) or macOS (menu bar).",
  },
  {
    key: "window.screenX",
    category: "window",
    severity: "low",
    description: "Window's screen X. 0 in headless; non-zero in real browsers when window isn't full-screen.",
  },
  {
    key: "window.screenY",
    category: "window",
    severity: "low",
    description: "Window's screen Y; same axis as screenX.",
  },
  {
    key: "screen.left",
    category: "screen",
    severity: "info",
    description: "Older alias of screenX in some browsers.",
  },
  {
    key: "screen.top",
    category: "screen",
    severity: "info",
    description: "Older alias of screenY.",
  },
  {
    key: "window.visualViewport",
    category: "window",
    severity: "medium",
    description: "VisualViewport. width/height/scale. When visualViewport.width === screen.width, the page is likely running headless / pinned-tab fullscreen.",
    botDetectionTell: true,
  },
  {
    key: "*.visualViewport",
    category: "window",
    severity: "medium",
    description: "Aliased visualViewport access (var v = window.visualViewport).",
  },
  {
    key: "showOpenFilePicker",
    category: "window",
    severity: "medium",
    description: "File System Access API. Chrome-desktop only — absence on a Chrome-desktop UA is a tell.",
    botDetectionTell: true,
  },
  {
    key: "showDirectoryPicker",
    category: "window",
    severity: "medium",
    description: "File System Access API directory picker; same Chrome-desktop signal.",
  },
  {
    key: "showSaveFilePicker",
    category: "window",
    severity: "low",
    description: "File System Access API save dialog.",
  },
  {
    key: "window.sidebar",
    category: "window",
    severity: "low",
    description: "Firefox-only object; presence pins Gecko engine even when UA spoofed.",
    botDetectionTell: true,
  },
  {
    key: "window.frames",
    category: "window",
    severity: "info",
    description: "Window.frames live list. window.frames.length and window.top !== window.self are used to detect iframed contexts.",
  },
  {
    key: "window.name",
    category: "window",
    severity: "low",
    description: "Persistent across same-tab navigations; used by some trackers to bridge identity across origins.",
  },
  {
    key: "crossOriginIsolated",
    category: "window",
    severity: "medium",
    description: "Boolean reflecting COOP+COEP. Required for SharedArrayBuffer in modern browsers — its value cross-checks the environment with the SharedArrayBuffer availability tell.",
    botDetectionTell: true,
  },
  {
    key: "ScreenDetailed",
    category: "screen",
    severity: "low",
    description: "Multi-screen Window Management API. Presence pins Chrome 100+; getScreenDetails() returns per-display geometry.",
  },
  {
    key: "*.getScreenDetails",
    category: "screen",
    severity: "low",
    description: "window.getScreenDetails(). Permission-gated multi-monitor probe.",
  },
];
